In [8]:
db_path_1 = r'C:\Users\trieu.pham\Dropbox\Projects\database\FCdata.db'
db_path_2 = r'C:\Users\PC\Dropbox\Projects\database\FCdata.db'
db_path_3 = '/Users/trieupham/Dropbox/Projects/database/FCdata.db'

directory_1 = r'C:\Users\trieu.pham\Dropbox\Projects\data_xls\detailTrans'
directory_2 = r'C:\Users\PC\Dropbox\Projects\data_xls\detailTrans'
directory_3 = '/Users/trieupham/Dropbox/Projects/data_xls/detailTrans'

import os
# Check if db_path exists
if os.path.exists(db_path_1):
    db_path = db_path_1
    directory = directory_1
if os.path.exists(db_path_2):
    db_path = db_path_2
    directory = directory_2
if os.path.exists(db_path_3):
    db_path = db_path_3
    directory = directory_3

In [9]:
# Load data from database, table: detail_Trans
import sqlite3
import pandas as pd
conn = sqlite3.connect(db_path)
query = 'SELECT * FROM detail_trans'
df = pd.read_sql_query(query, conn)
conn.close()

df

,invoiceDate,invoiceCode,storeCode,employeeCode,employeeName,storeName,barcode,itemName,qty,unitPrice,...,VNPAY,VND,MOMO,OCB-eBank,ZaloPay,e-Voucher,GrabOrder,ShopeeFood,Membership,ShopeePay
0,20/06/2024 13:03:11,VN0265012006240042,VN0265,F231230010,Nguyễn Ngọc Huỳnh Như,GS25 Hoang Anh Thanh Binh_FC,8934564600838,C2 Trà xanh chanh tuyết bạc hà 455ml x chai,1,12000,...,32000.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,20/06/2024 13:03:11,VN0265012006240042,VN0265,F231230010,Nguyễn Ngọc Huỳnh Như,GS25 Hoang Anh Thanh Binh_FC,2701020000091,HĐ Cơm nắm bò bulgogi phô mai x cái,1,20000,...,32000.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,20/06/2024 13:12:08,VN0265012006240043,VN0265,F231230010,Nguyễn Ngọc Huỳnh Như,GS25 Hoang Anh Thanh Binh_FC,2010103000010,Milo ly lớn x 1ly,1,25000,...,0.0,25000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,20/06/2024 17:37:35,VN0265012006240097,VN0265,F231230003,Hồ Tuyết Nhi,GS25 Hoang Anh Thanh Binh_FC,6976611080066,QNL Mayeef bánh phô mai x cái,1,17000,...,0.0,0.0,17000.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,20/06/2024 08:33:20,VN0265022006240053,VN0265,F240106001,nguyễn ngọc tuấn,GS25 Hoang Anh Thanh Binh_FC,2503020188829,Cà phê sữa GS25 x ly,1,20000,...,0.0,0.0,0.0,33000.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21843,04/07/2024 12:15:14,VN0265020407240080,VN0265,F240427001,Lê Thị Ngọc Ánh,GS25 Hoang Anh Thanh Binh_FC,2010906000095,HĐ Mỳ ý sốt kem thịt xông khói x hộp,1,39000,...,0.0,44000.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
21844,04/07/2024 12:15:14,VN0265020407240080,VN0265,F240427001,Lê Thị Ngọc Ánh,GS25 Hoang Anh Thanh Binh_FC,8935049500698,FUZETEA+ Trà đào hạt chia 450ml x chai,1,11000,...,0.0,44000.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
21845,04/07/2024 06:25:54,VN0265020407240002,VN0265,F240215002,HUỲNH THỊ KIM NGỌC,GS25 Hoang Anh Thanh Binh_FC,8938502525368,Bánh bao nhân thịt heo trứng muối xá xíu,1,29000,...,0.0,29000.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
21846,04/07/2024 17:59:51,VN0265020407240144,VN0265,F240106001,nguyễn ngọc tuấn,GS25 Hoang Anh Thanh Binh_FC,8997035600645,POCARI Sweat 350ml x chai,1,13000,...,0.0,13000.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
21847,04/07/2024 16:22:35,VN0265020407240120,VN0265,F240106001,nguyễn ngọc tuấn,GS25 Hoang Anh Thanh Binh_FC,2010901000120,HĐ Cơm gà sốt Hàn Quốc x hộp,1,38000,...,0.0,38000.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0

In [10]:
# Query data from database to get list of unique employeeName
conn = sqlite3.connect(db_path)
query = 'SELECT DISTINCT employeeName FROM detail_Trans'
df_unique_emp = pd.read_sql_query(query, conn)
conn.close()

# Get list of unique employeeName
employeeName_list = df_unique_emp['employeeName'].tolist()
employeeName_list

['Nguyễn Ngọc Huỳnh Như',
 'Hồ Tuyết Nhi',
 'nguyễn ngọc tuấn',
 'Tằng Cắm Út',
 'Thi Đỗ Kim Thanh',
 'Lê Thị Ngọc Ánh ',
 'HUỲNH THỊ KIM NGỌC',
 'Dương Linh Chi',
 'LÊ THỊ HOÀI',
 'Huỳnh Thị Trà Mi']

In [11]:

df['invoiceDate'] = pd.to_datetime(df['invoiceDate'])
#df_filter

C:\Users\trieu.pham\AppData\Local\Temp\ipykernel_22532\147192335.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['invoiceDate'] = pd.to_datetime(df['invoiceDate'])

In [12]:
import pandas as pd

df_filter = df[(df['employeeName'] == 'Lê Thị Ngọc Ánh')  & (df['invoiceDate'] >= '2024-07-02 00:00:00') & (df['invoiceDate'] <= '2024-07-02 23:59:00') & (df['VND'] > 0.0)]
# Sort df_filter by invoiceDate
df_filter = df_filter.sort_values(by='invoiceDate')
# Check if there are any NaN values after conversion (indicating non-numeric values were present)
if df_filter['VND'].isnull().any():
    print('VND column has non-numeric value')
else:
    # Sum of unitPrice column
    sum_unitPrice = df_filter['unitPrice'].sum()

    # create a new dataframe, which contains unique invoiceCode
    df_filter_unique = df_filter.drop_duplicates(subset='invoiceCode')
    sum_VND = df_filter_unique['VND'].sum()

# format sum_VND to currency
sum_VND = '{:,.0f}'.format(sum_VND)
print('Sum of VND: ', sum_VND)

Sum of VND:  0

In [13]:
import pandas as pd

# Assuming df is your original dataframe

# Filter df for invoiceDate and VND conditions
df_filter = df[(df['invoiceDate'] >= '2024-07-03 21:00:00') & (df['invoiceDate'] <= '2024-07-04 23:00:00') & (df['VND'] > 0.0)]

# Sort df_filter by invoiceDate
df_filter = df_filter.sort_values(by='invoiceDate')

# Check if there are any NaN values in the VND column
if df_filter['VND'].isnull().any():
    print('VND column has non-numeric value')
else:
    # Group by employeeName and calculate sum of VND for each group
    sum_VND_by_employee = df_filter.drop_duplicates(subset='invoiceCode').groupby('employeeName')['VND'].sum()

    # Iterate over each employee and print the sum of VND
    for employee, sum_VND in sum_VND_by_employee.items():
        # Format sum_VND to currency
        formatted_sum_VND = '{:,.0f}'.format(sum_VND)
        print(f'Sum of VND for {employee}: {formatted_sum_VND}')
    # Calculate total sum of VND
    total_sum_VND = sum_VND_by_employee.sum()
    print(f'Total sum of VND: {total_sum_VND:,.0f}')

Sum of VND for Dương Linh Chi: 1,426,000
Sum of VND for HUỲNH THỊ KIM NGỌC: 1,304,000
Sum of VND for Huỳnh Thị Trà Mi: 871,000
Sum of VND for Hồ Tuyết Nhi: 520,000
Sum of VND for Lê Thị Ngọc Ánh : 2,014,000
Sum of VND for Thi Đỗ Kim Thanh: 129,000
Sum of VND for Tằng Cắm Út: 2,781,000
Sum of VND for nguyễn ngọc tuấn: 1,024,000
Total sum of VND: 10,069,000