In [12]:
try:
    import pyodbc
except ImportError:
    print("pyodbc module not found. Install it with 'pip install pyodbc'")
    exit(1)

# List all available ODBC drivers
drivers = pyodbc.drivers()

if drivers:
    print("ODBC drivers installed on your system:")
    for driver in drivers:
        print(driver)
else:
    print("No ODBC drivers found on your system.")

ODBC drivers installed on your system:
SQL Server

In [19]:
import pandas as pd
from sqlalchemy import create_engine

# Replace the connection string with your actual SQL Server details
connection_string = (
    'mssql+pyodbc://pos:pos@vnsulataxs7db01.clienttest.btmgcs.com/xcenter?driver=SQL+Server'
)

# Create an SQLAlchemy engine
engine = create_engine(connection_string)

# Read the mapping CSV file
mapping_df = pd.read_csv(r'C:\Users\trieu.pham\Downloads\Mapping.csv')

# Extract the list of tables from the "v7" column
tables = mapping_df['v7'].tolist()

template = "SELECT * FROM {table} WHERE rtl_loc_id = '51' AND {table}.business_date > '2023-05-14' ORDER BY trans_seq;"
template2 = "SELECT * FROM {table} WHERE create_date > '2023-05-14';"

# Location to export csv files
output_folder = r'C:\Users\trieu.pham\Downloads\Data Migration'
# Clear all csv files in the output folder
import os
import glob
files = glob.glob(output_folder + '/*.csv')
for f in files:
    os.remove(f)

for table in tables:
    # Try to check using the first template
    try:
        sql_query = template.format(table=table)
        df = pd.read_sql_query(sql_query, engine)
    except Exception as e:
        print(f"Failed to execute the query with the first template for table '{table}': {e}")
        # Export fail table to a CSV file in the output_folder, then skip to the next table
        csv_filename = f"{output_folder}/{table}_fail.csv"
        print("Trying the second template...")

        # Try to check using the second template
        try:
            sql_query = template2.format(table=table)
            df = pd.read_sql_query(sql_query, engine)
        except Exception as e:
            print(f"Failed to execute the query with the second template for table '{table}': {e}")
            continue

    # Export the DataFrame to a CSV file in the output_folder
    csv_filename = f"{output_folder}/{table}_v7.csv"
    df.to_csv(csv_filename, index=False)
    print(f"Exported {table} to {csv_filename}")

# Close the database connection
engine.dispose()

print("All operations completed.")

Exported trn_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_v7.csv
Exported trn_post_void_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_post_void_trans_v7.csv
Exported trn_trans_version to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_version_v7.csv
Exported trn_poslog_data to C:\Users\trieu.pham\Downloads\Data Migration/trn_poslog_data_v7.csv
Exported trn_receipt_lookup to C:\Users\trieu.pham\Downloads\Data Migration/trn_receipt_lookup_v7.csv
Exported trn_receipt_data to C:\Users\trieu.pham\Downloads\Data Migration/trn_receipt_data_v7.csv
Exported trn_trans_link to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_link_v7.csv
Exported trn_trans_notes to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_notes_v7.csv
Exported trn_trans_properties to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_properties_v7.csv
Exported trn_no_sale_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_no_sale_trans_v7.csv
Exported trl_rtrans to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtrans_v7.csv
Exported trl_rtrans_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtrans_lineitm_v7.csv
Exported trl_commission_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_commission_mod_v7.csv
Exported trl_sale_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_sale_lineitm_v7.csv
Exported trl_inventory_loc_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_inventory_loc_mod_v7.csv
Exported trl_returned_item_count to C:\Users\trieu.pham\Downloads\Data Migration/trl_returned_item_count_v7.csv
Exported trl_returned_item_journal to C:\Users\trieu.pham\Downloads\Data Migration/trl_returned_item_journal_v7.csv
Exported trl_sale_tax_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_sale_tax_lineitm_v7.csv
Exported trl_tax_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_tax_lineitm_v7.csv
Exported trl_warranty_modifier to C:\Users\trieu.pham\Downloads\Data Migration/trl_warranty_modifier_v7.csv
Exported trl_lineitm_notes to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_notes_v7.csv
Exported trl_lineitm_properties to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_properties_v7.csv
Exported trl_cust_item_acct_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_cust_item_acct_mod_v7.csv
Exported trl_correction_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_correction_mod_v7.csv
Failed to execute the query with the first template for table 'trl_lineitm_assoc_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM trl_lineitm_assoc_mod WHERE rtl_loc_id = '51' AND trl_lineitm_assoc_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported trl_lineitm_assoc_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_assoc_mod_v7.csv
Failed to execute the query with the first template for table 'trl_lineitm_assoc_typcode': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM trl_lineitm_assoc_typcode WHERE rtl_loc_id = '51' AND trl_lineitm_assoc_typcode.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported trl_lineitm_assoc_typcode to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_assoc_typcode_v7.csv
Exported trl_discount_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_discount_lineitm_v7.csv
Exported trl_rtl_price_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtl_price_mod_v7.csv
Exported trl_deal_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_deal_lineitm_v7.csv
Exported trl_voucher_sale_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_voucher_sale_lineitm_v7.csv
Exported trl_coupon_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_coupon_lineitm_v7.csv
Exported ttr_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_tndr_lineitm_v7.csv
Exported ttr_acct_credit_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_acct_credit_tndr_lineitm_v7.csv
Exported ttr_credit_debit_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_credit_debit_tndr_lineitm_v7.csv
Exported ttr_signature to C:\Users\trieu.pham\Downloads\Data Migration/ttr_signature_v7.csv
Failed to execute the query with the first template for table 'ttr_voucher': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM ttr_voucher WHERE rtl_loc_id = '51' AND ttr_voucher.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported ttr_voucher to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_v7.csv
Exported ttr_voucher_history to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_history_v7.csv
Exported ttr_voucher_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_tndr_lineitm_v7.csv
Exported ttr_tndr_auth_log to C:\Users\trieu.pham\Downloads\Data Migration/ttr_tndr_auth_log_v7.csv
Exported ttr_check_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_check_tndr_lineitm_v7.csv
Exported ttr_send_check_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_send_check_tndr_lineitm_v7.csv
Exported ttr_coupon_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_coupon_tndr_lineitm_v7.csv
Failed to execute the query with the first template for table 'xom_address_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_address_mod WHERE rtl_loc_id = '51' AND xom_address_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_address_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_address_mod_v7.csv
Failed to execute the query with the first template for table 'xom_balance_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_balance_mod WHERE rtl_loc_id = '51' AND xom_balance_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_balance_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_balance_mod_v7.csv
Failed to execute the query with the first template for table 'xom_customer_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_customer_mod WHERE rtl_loc_id = '51' AND xom_customer_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_customer_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_customer_mod_v7.csv
Failed to execute the query with the first template for table 'xom_fee_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_fee_mod WHERE rtl_loc_id = '51' AND xom_fee_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_fee_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_fee_mod_v7.csv
Failed to execute the query with the first template for table 'xom_fulfillment_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_fulfillment_mod WHERE rtl_loc_id = '51' AND xom_fulfillment_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_fulfillment_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_fulfillment_mod_v7.csv
Failed to execute the query with the first template for table 'xom_item_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_item_mod WHERE rtl_loc_id = '51' AND xom_item_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_item_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_item_mod_v7.csv
Failed to execute the query with the first template for table 'xom_order': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order WHERE rtl_loc_id = '51' AND xom_order.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_v7.csv
Failed to execute the query with the first template for table 'xom_order_fee': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_fee WHERE rtl_loc_id = '51' AND xom_order_fee.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_fee to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_fee_v7.csv
Failed to execute the query with the first template for table 'xom_order_line': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_line WHERE rtl_loc_id = '51' AND xom_order_line.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_line to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_line_v7.csv
Failed to execute the query with the first template for table 'xom_order_line': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_line WHERE rtl_loc_id = '51' AND xom_order_line.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_line to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_line_v7.csv
Exported xom_order_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_mod_v7.csv
Failed to execute the query with the first template for table 'xom_order_payment': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_payment WHERE rtl_loc_id = '51' AND xom_order_payment.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_payment to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_payment_v7.csv
Failed to execute the query with the first template for table 'xom_source_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_source_mod WHERE rtl_loc_id = '51' AND xom_source_mod.business_date > '2023-05-14' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_source_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_source_mod_v7.csv
Exported trl_correction_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_correction_mod_v7.csv
Exported ttr_identity_verification to C:\Users\trieu.pham\Downloads\Data Migration/ttr_identity_verification_v7.csv
All operations completed.

In [21]:
import pandas as pd
from sqlalchemy import create_engine

# Replace the connection string with your actual SQL Server details
connection_string = (
    'mssql+pyodbc://dtv:dtv@sulata-xu-02.cust.sgn.btmglobal.org/xcenter?driver=SQL+Server'
)

# Create an SQLAlchemy engine
engine = create_engine(connection_string)

# Read the mapping CSV file
mapping_df = pd.read_csv(r'C:\Users\trieu.pham\Downloads\Mapping.csv')

# Extract the list of tables from the "v7" column
tables = mapping_df['v23'].tolist()

template = "SELECT * FROM {table} WHERE rtl_loc_id = '51' AND {table}.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;"
template2 = "SELECT * FROM {table} WHERE create_user_id = 'DC_User';"

# Location to export csv files
output_folder = r'C:\Users\trieu.pham\Downloads\Data Migration'

for table in tables:
    # Try to check using the first template
    try:
        sql_query = template.format(table=table)
        df = pd.read_sql_query(sql_query, engine)
    except Exception as e:
        print(f"Failed to execute the query with the first template for table '{table}': {e}")
        # Export fail table to a CSV file in the output_folder, then skip to the next table
        csv_filename = f"{output_folder}/{table}_fail.csv"
        print("Trying the second template...")

        # Try to check using the second template
        try:
            sql_query = template2.format(table=table)
            df = pd.read_sql_query(sql_query, engine)
        except Exception as e:
            print(f"Failed to execute the query with the second template for table '{table}': {e}")
            continue

    # Export the DataFrame to a CSV file in the output_folder
    csv_filename = f"{output_folder}/{table}_v23.csv"
    df.to_csv(csv_filename, index=False)
    print(f"Exported {table} to {csv_filename}")

# Close the database connection
engine.dispose()

print("All operations completed.")

Exported trn_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_v23.csv
Exported trn_post_void_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_post_void_trans_v23.csv
Exported trn_trans_version to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_version_v23.csv
Exported trn_poslog_data to C:\Users\trieu.pham\Downloads\Data Migration/trn_poslog_data_v23.csv
Exported trn_receipt_lookup to C:\Users\trieu.pham\Downloads\Data Migration/trn_receipt_lookup_v23.csv
Exported trn_receipt_data to C:\Users\trieu.pham\Downloads\Data Migration/trn_receipt_data_v23.csv
Exported trn_trans_link to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_link_v23.csv
Exported trn_trans_notes to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_notes_v23.csv
Exported trn_trans_p to C:\Users\trieu.pham\Downloads\Data Migration/trn_trans_p_v23.csv
Exported trn_no_sale_trans to C:\Users\trieu.pham\Downloads\Data Migration/trn_no_sale_trans_v23.csv
Exported trl_rtrans to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtrans_v23.csv
Exported trl_rtrans_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtrans_lineitm_v23.csv
Exported trl_commission_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_commission_mod_v23.csv
Exported trl_sale_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_sale_lineitm_v23.csv
Exported trl_inventory_loc_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_inventory_loc_mod_v23.csv
Exported trl_returned_item_count to C:\Users\trieu.pham\Downloads\Data Migration/trl_returned_item_count_v23.csv
Exported trl_returned_item_journal to C:\Users\trieu.pham\Downloads\Data Migration/trl_returned_item_journal_v23.csv
Exported trl_sale_tax_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_sale_tax_lineitm_v23.csv
Exported trl_tax_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_tax_lineitm_v23.csv
Exported trl_warranty_modifier to C:\Users\trieu.pham\Downloads\Data Migration/trl_warranty_modifier_v23.csv
Exported trl_lineitm_notes to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_notes_v23.csv
Exported trl_rtrans_lineitm_p to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtrans_lineitm_p_v23.csv
Exported trl_cust_item_acct_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_cust_item_acct_mod_v23.csv
Exported trl_correction_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_correction_mod_v23.csv
Failed to execute the query with the first template for table 'trl_lineitm_assoc_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM trl_lineitm_assoc_mod WHERE rtl_loc_id = '51' AND trl_lineitm_assoc_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported trl_lineitm_assoc_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_assoc_mod_v23.csv
Failed to execute the query with the first template for table 'trl_lineitm_assoc_typcode': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM trl_lineitm_assoc_typcode WHERE rtl_loc_id = '51' AND trl_lineitm_assoc_typcode.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported trl_lineitm_assoc_typcode to C:\Users\trieu.pham\Downloads\Data Migration/trl_lineitm_assoc_typcode_v23.csv
Exported trl_discount_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_discount_lineitm_v23.csv
Exported trl_rtl_price_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_rtl_price_mod_v23.csv
Exported trl_deal_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_deal_lineitm_v23.csv
Exported trl_voucher_sale_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_voucher_sale_lineitm_v23.csv
Exported trl_coupon_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/trl_coupon_lineitm_v23.csv
Exported ttr_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_tndr_lineitm_v23.csv
Exported ttr_acct_credit_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_acct_credit_tndr_lineitm_v23.csv
Exported ttr_credit_debit_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_credit_debit_tndr_lineitm_v23.csv
Exported ttr_signature to C:\Users\trieu.pham\Downloads\Data Migration/ttr_signature_v23.csv
Failed to execute the query with the first template for table 'ttr_voucher': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM ttr_voucher WHERE rtl_loc_id = '51' AND ttr_voucher.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported ttr_voucher to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_v23.csv
Exported ttr_voucher_history to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_history_v23.csv
Exported ttr_voucher_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_voucher_tndr_lineitm_v23.csv
Exported ttr_tndr_auth_log to C:\Users\trieu.pham\Downloads\Data Migration/ttr_tndr_auth_log_v23.csv
Exported ttr_check_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_check_tndr_lineitm_v23.csv
Exported ttr_send_check_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_send_check_tndr_lineitm_v23.csv
Exported ttr_coupon_tndr_lineitm to C:\Users\trieu.pham\Downloads\Data Migration/ttr_coupon_tndr_lineitm_v23.csv
Failed to execute the query with the first template for table 'xom_address_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_address_mod WHERE rtl_loc_id = '51' AND xom_address_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_address_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_address_mod_v23.csv
Failed to execute the query with the first template for table 'xom_balance_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_balance_mod WHERE rtl_loc_id = '51' AND xom_balance_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_balance_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_balance_mod_v23.csv
Failed to execute the query with the first template for table 'xom_customer_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_customer_mod WHERE rtl_loc_id = '51' AND xom_customer_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_customer_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_customer_mod_v23.csv
Failed to execute the query with the first template for table 'xom_fee_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_fee_mod WHERE rtl_loc_id = '51' AND xom_fee_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_fee_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_fee_mod_v23.csv
Failed to execute the query with the first template for table 'xom_fulfillment_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_fulfillment_mod WHERE rtl_loc_id = '51' AND xom_fulfillment_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_fulfillment_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_fulfillment_mod_v23.csv
Failed to execute the query with the first template for table 'xom_item_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_item_mod WHERE rtl_loc_id = '51' AND xom_item_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_item_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_item_mod_v23.csv
Failed to execute the query with the first template for table 'xom_order': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order WHERE rtl_loc_id = '51' AND xom_order.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_v23.csv
Failed to execute the query with the first template for table 'xom_order_fee': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_fee WHERE rtl_loc_id = '51' AND xom_order_fee.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_fee to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_fee_v23.csv
Failed to execute the query with the first template for table 'xom_order_line': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_line WHERE rtl_loc_id = '51' AND xom_order_line.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_line to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_line_v23.csv
Failed to execute the query with the first template for table 'xom_order_line_detail': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_line_detail WHERE rtl_loc_id = '51' AND xom_order_line_detail.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_line_detail to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_line_detail_v23.csv
Exported xom_order_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_mod_v23.csv
Failed to execute the query with the first template for table 'xom_order_payment': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_order_payment WHERE rtl_loc_id = '51' AND xom_order_payment.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_order_payment to C:\Users\trieu.pham\Downloads\Data Migration/xom_order_payment_v23.csv
Failed to execute the query with the first template for table 'xom_source_mod': (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'rtl_loc_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'business_date'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'trans_seq'. (207)")
[SQL: SELECT * FROM xom_source_mod WHERE rtl_loc_id = '51' AND xom_source_mod.business_date > '2023-05-14' AND create_user_id = 'DC_User' ORDER BY trans_seq;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Trying the second template...
Exported xom_source_mod to C:\Users\trieu.pham\Downloads\Data Migration/xom_source_mod_v23.csv
Exported trl_correction_mod to C:\Users\trieu.pham\Downloads\Data Migration/trl_correction_mod_v23.csv
Exported ttr_identity_verification to C:\Users\trieu.pham\Downloads\Data Migration/ttr_identity_verification_v23.csv
All operations completed.

In [22]:
import pandas as pd
import os

# Read the mapping CSV file
mapping_df = pd.read_csv(r'C:\Users\trieu.pham\Downloads\Mapping.csv')

# Location of the exported CSV files
v7_folder = r'C:\Users\trieu.pham\Downloads\Data Migration'
v23_folder = r'C:\Users\trieu.pham\Downloads\Data Migration'

# Location to save the comparison results and failed comparisons
output_folder = r'C:\Users\trieu.pham\Downloads\Data Migration\comparison_results'
failed_folder = r'C:\Users\trieu.pham\Downloads\Data Migration\failed_queries'
nodiff_folder = r'C:\Users\trieu.pham\Downloads\Data Migration\no_diff'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)
if not os.path.exists(failed_folder):
    os.makedirs(failed_folder)
if not os.path.exists(nodiff_folder):
    os.makedirs(nodiff_folder)

# Clear output folder and failed folder before starting
for file in os.listdir(output_folder):
    os.remove(os.path.join(output_folder, file))
for file in os.listdir(failed_folder):
    os.remove(os.path.join(failed_folder, file))
for file in os.listdir(nodiff_folder):
    os.remove(os.path.join(nodiff_folder, file))

# Columns to exclude from the comparison
exclude_columns = ['create_date', 'create_user_id', 'update_date', 'update_user_id']

# Function to compare two CSV files based on primary keys
def compare_csv_files(file1, file2, exclude_cols, primary_keys):
    df1 = pd.read_csv(file1)
    df2 = pd.read_csv(file2)
    
    exclude_cols = [col for col in exclude_cols if col not in primary_keys]
    
    df1_compare = df1.drop(columns=exclude_cols, errors='ignore')
    df2_compare = df2.drop(columns=exclude_cols, errors='ignore')
    
    # Align the columns of both DataFrames
    combined_columns = df1_compare.columns.union(df2_compare.columns)
    df1_compare = df1_compare.reindex(columns=combined_columns).sort_index(axis=1)
    df2_compare = df2_compare.reindex(columns=combined_columns).sort_index(axis=1)
    
    # Ensure both DataFrames have the same index
    df1_compare = df1_compare.reset_index(drop=True)
    df2_compare = df2_compare.reset_index(drop=True)
    
    # Merge DataFrames on primary keys to ensure aligned comparison
    merge_keys = [key for key in primary_keys if key in df1_compare.columns and key in df2_compare.columns]
    if not merge_keys:
        raise ValueError("No common primary keys found for comparison.")
    
    merged_df = pd.merge(df1_compare, df2_compare, on=merge_keys, suffixes=('_v7', '_v23'))
    
    # Separate the columns to compare
    v7_columns = [col for col in merged_df.columns if col.endswith('_v7')]
    v23_columns = [col for col in merged_df.columns if col.endswith('_v23')]
    
    # Create DataFrames for comparison
    df_v7 = merged_df[v7_columns]
    df_v23 = merged_df[v23_columns]
    
    # Remove suffixes to match columns
    df_v7.columns = df_v7.columns.str.replace('_v7', '')
    df_v23.columns = df_v23.columns.str.replace('_v23', '')
    
    # Compare the DataFrames
    comparison_result = df_v7.compare(df_v23)
    
    # Add primary keys to the comparison result for tracking if they exist and if there are differences
    if not comparison_result.empty:
        for key in merge_keys:
            comparison_result[key] = merged_df[key]
    
    return comparison_result

# Loop through the mapping and compare the respective CSV files
for index, row in mapping_df.iterrows():
    v7_table = row['v7']
    v23_table = row['v23']
    
    # Determine the primary keys based on table name
    if v7_table.startswith('xom_'):
        primary_keys = ['order_id']
    else:
        primary_keys = ['trans_seq', 'rtrans_lineitm_seq']
    
    v7_file = f"{v7_folder}/{v7_table}_v7.csv"
    v23_file = f"{v23_folder}/{v23_table}_v23.csv"
    
    try:
        comparison_result = compare_csv_files(v7_file, v23_file, exclude_columns, primary_keys)
        
        if not comparison_result.empty:
            # Save the comparison result to a CSV file
            comparison_result_file = f"{output_folder}/comparison_{v7_table}_vs_{v23_table}.csv"
            comparison_result.to_csv(comparison_result_file, index=False)
            print(f"Differences found for {v7_table} vs {v23_table} and saved to {comparison_result_file}")
        else:
            print(f"No differences found for {v7_table} vs {v23_table}")
            # Save no differences found to a CSV file
            no_diff_file = f"{nodiff_folder}/no_diff_{v7_table}_vs_{v23_table}.csv"
            with open(no_diff_file, 'w') as f:
                f.write('No differences found')
    
    except Exception as e:
        print(f"Failed to compare {v7_table} with {v23_table}: {e}")
        # Save the error details to the failed folder
        error_details = {
            'v7_table': [v7_table],
            'v23_table': [v23_table],
            'error': [str(e)]
        }
        failed_comparison_df = pd.DataFrame(error_details)
        failed_comparison_file = f"{failed_folder}/failed_comparison_{v7_table}_vs_{v23_table}.csv"
        failed_comparison_df.to_csv(failed_comparison_file, index=False)

print("Comparison completed.")

Differences found for trn_trans vs trn_trans and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trn_trans_vs_trn_trans.csv
No differences found for trn_post_void_trans vs trn_post_void_trans
No differences found for trn_trans_version vs trn_trans_version
Differences found for trn_poslog_data vs trn_poslog_data and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trn_poslog_data_vs_trn_poslog_data.csv
Differences found for trn_receipt_lookup vs trn_receipt_lookup and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trn_receipt_lookup_vs_trn_receipt_lookup.csv
Differences found for trn_receipt_data vs trn_receipt_data and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trn_receipt_data_vs_trn_receipt_data.csv
No differences found for trn_trans_link vs trn_trans_link
No differences found for trn_trans_notes vs trn_trans_notes
Differences found for trn_trans_properties vs trn_trans_p and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trn_trans_properties_vs_trn_trans_p.csv
No differences found for trn_no_sale_trans vs trn_no_sale_trans
No differences found for trl_rtrans vs trl_rtrans
Differences found for trl_rtrans_lineitm vs trl_rtrans_lineitm and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trl_rtrans_lineitm_vs_trl_rtrans_lineitm.csv
No differences found for trl_commission_mod vs trl_commission_mod
Differences found for trl_sale_lineitm vs trl_sale_lineitm and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trl_sale_lineitm_vs_trl_sale_lineitm.csv
No differences found for trl_inventory_loc_mod vs trl_inventory_loc_mod
No differences found for trl_returned_item_count vs trl_returned_item_count
No differences found for trl_returned_item_journal vs trl_returned_item_journal
Differences found for trl_sale_tax_lineitm vs trl_sale_tax_lineitm and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trl_sale_tax_lineitm_vs_trl_sale_tax_lineitm.csv
No differences found for trl_tax_lineitm vs trl_tax_lineitm
No differences found for trl_warranty_modifier vs trl_warranty_modifier
No differences found for trl_lineitm_notes vs trl_lineitm_notes
Differences found for trl_lineitm_properties vs trl_rtrans_lineitm_p and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trl_lineitm_properties_vs_trl_rtrans_lineitm_p.csv
No differences found for trl_cust_item_acct_mod vs trl_cust_item_acct_mod
No differences found for trl_correction_mod vs trl_correction_mod
Failed to compare trl_lineitm_assoc_mod with trl_lineitm_assoc_mod: No common primary keys found for comparison.
Failed to compare trl_lineitm_assoc_typcode with trl_lineitm_assoc_typcode: No common primary keys found for comparison.
No differences found for trl_discount_lineitm vs trl_discount_lineitm
Differences found for trl_rtl_price_mod vs trl_rtl_price_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_trl_rtl_price_mod_vs_trl_rtl_price_mod.csv
No differences found for trl_deal_lineitm vs trl_deal_lineitm
No differences found for trl_voucher_sale_lineitm vs trl_voucher_sale_lineitm
No differences found for trl_coupon_lineitm vs trl_coupon_lineitm
No differences found for ttr_tndr_lineitm vs ttr_tndr_lineitm
No differences found for ttr_acct_credit_tndr_lineitm vs ttr_acct_credit_tndr_lineitm
Differences found for ttr_credit_debit_tndr_lineitm vs ttr_credit_debit_tndr_lineitm and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_ttr_credit_debit_tndr_lineitm_vs_ttr_credit_debit_tndr_lineitm.csv
No differences found for ttr_signature vs ttr_signature
Failed to compare ttr_voucher with ttr_voucher: No common primary keys found for comparison.
No differences found for ttr_voucher_history vs ttr_voucher_history
No differences found for ttr_voucher_tndr_lineitm vs ttr_voucher_tndr_lineitm
Differences found for ttr_tndr_auth_log vs ttr_tndr_auth_log and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_ttr_tndr_auth_log_vs_ttr_tndr_auth_log.csv
No differences found for ttr_check_tndr_lineitm vs ttr_check_tndr_lineitm
No differences found for ttr_send_check_tndr_lineitm vs ttr_send_check_tndr_lineitm
No differences found for ttr_coupon_tndr_lineitm vs ttr_coupon_tndr_lineitm
Differences found for xom_address_mod vs xom_address_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_address_mod_vs_xom_address_mod.csv
Differences found for xom_balance_mod vs xom_balance_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_balance_mod_vs_xom_balance_mod.csv
Differences found for xom_customer_mod vs xom_customer_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_customer_mod_vs_xom_customer_mod.csv
Differences found for xom_fee_mod vs xom_fee_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_fee_mod_vs_xom_fee_mod.csv
Differences found for xom_fulfillment_mod vs xom_fulfillment_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_fulfillment_mod_vs_xom_fulfillment_mod.csv
Differences found for xom_item_mod vs xom_item_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_item_mod_vs_xom_item_mod.csv
Differences found for xom_order vs xom_order and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_order_vs_xom_order.csv
No differences found for xom_order_fee vs xom_order_fee
Differences found for xom_order_line vs xom_order_line and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_order_line_vs_xom_order_line.csv
Differences found for xom_order_line vs xom_order_line_detail and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_order_line_vs_xom_order_line_detail.csv
Differences found for xom_order_mod vs xom_order_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_order_mod_vs_xom_order_mod.csv
Differences found for xom_order_payment vs xom_order_payment and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_order_payment_vs_xom_order_payment.csv
Differences found for xom_source_mod vs xom_source_mod and saved to C:\Users\trieu.pham\Downloads\Data Migration\comparison_results/comparison_xom_source_mod_vs_xom_source_mod.csv
No differences found for trl_correction_mod vs trl_correction_mod
No differences found for ttr_identity_verification vs ttr_identity_verification
Comparison completed.

In [23]:
import pandas as pd

def compare_csv_files(file1, file2, output_file, primary_keys, duplicates_file):
    df1 = pd.read_csv(file1)
    df2 = pd.read_csv(file2)
    
    # Identify and export duplicates in the primary key columns
    duplicates_df1 = df1[df1.duplicated(subset=primary_keys, keep=False)]
    duplicates_df2 = df2[df2.duplicated(subset=primary_keys, keep=False)]
    
    if not duplicates_df1.empty or not duplicates_df2.empty:
        duplicates = pd.concat([duplicates_df1, duplicates_df2])
        duplicates.to_csv(duplicates_file, index=False)
        print(f"Duplicates found and saved to {duplicates_file}")
        
    # Remove duplicates
    df1 = df1.drop_duplicates(subset=primary_keys)
    df2 = df2.drop_duplicates(subset=primary_keys)
    
    # Set primary keys as index
    df1.set_index(primary_keys, inplace=True)
    df2.set_index(primary_keys, inplace=True)
    
    # Align the columns of both DataFrames
    combined_columns = df1.columns.union(df2.columns)
    df1 = df1.reindex(columns=combined_columns)
    df2 = df2.reindex(columns=combined_columns)
    
    # Ensure both DataFrames have the same index
    combined_index = df1.index.union(df2.index)
    df1 = df1.reindex(combined_index)
    df2 = df2.reindex(combined_index)
    
    # Compare the DataFrames
    comparison_result = df1.compare(df2)
    
    # Add primary keys to the comparison result for tracking if they exist and if there are differences
    if not comparison_result.empty:
        for key in primary_keys:
            comparison_result[key] = combined_index.get_level_values(key)
    
    # Save the comparison result to a CSV file
    comparison_result.to_csv(output_file)
    print(f"Differences saved to {output_file}")

# Example usage
file1 = r'C:\Users\trieu.pham\Dropbox\Projects\data_csv\Data Migration\xom_address_mod_v7.csv'
file2 = r'C:\Users\trieu.pham\Dropbox\Projects\data_csv\Data Migration\xom_address_mod_v23.csv'
output_file = r'C:\Users\trieu.pham\Dropbox\Projects\data_csv\Data Migration\output_comparison.csv'
duplicates_file = r'C:\Users\trieu.pham\Dropbox\Projects\data_csv\Data Migration\duplicates.csv'
primary_keys = ['order_id', 'address_seq']

compare_csv_files(file1, file2, output_file, primary_keys, duplicates_file)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\trieu.pham\\Dropbox\\Projects\\data_csv\\Data Migration\\xom_address_mod_v7.csv'